### ISSUE TITLE
Exception for CPU collection

### ISSUE THREAD

**Issue by MyungChi** [cha87de/kvmtop#21]
Hi. 

I have met one more error as below. with some VM. When I run this VM. kvmtop has downed with below error.

I want to use kvmtop in my kvm resource collector. Would you fix and release new binary ASAP ?

```
# kvmtop --cpu

 cpu
 cores
 meanfreq panic: runtime error: index out of range
goroutine 18 [running]:
github.com/cha87de/kvmtop/collectors/cpucollector.cpuLookup(0xc4202cbba8, 0x7fe978000b40)
/home/travis/gopath/src/github.com/cha87de/kvmtop/collectors/cpucollector/worker.go:67 +0x6b6
github.com/cha87de/kvmtop/collectors/cpucollector.(*Collector).Lookup.func1(0x8048c0, 0xc420162c20, 0x8682c0, 0xc42008f830, 0x200202a0101)
 /home/travis/gopath/src/github.com/cha87de/kvmtop/collectors/cpucollector/collector.go:19 +0x10b
sync.(*Map).Range(0xc92a68, 0x89d9e8)
/home/travis/.gimme/versions/go1.9.linux.amd64/src/sync/map.go:336 +0x150
github.com/cha87de/kvmtop/collectors/cpucollector.(*Collector).Lookup(0xc4200576e0)
/home/travis/gopath/src/github.com/cha87de/kvmtop/collectors/cpucollector/collector.go:15 +0x39
github.com/cha87de/kvmtop/runners.lookup.func2(0x8048c0, 0xc4200576f0, 0x830600, 0xc4200576e0, 0x8048c0)
/home/travis/gopath/src/github.com/cha87de/kvmtop/runners/lookup.go:65 +0x55
sync.(*Map).Range(0xc92a90, 0x89da60)
/home/travis/.gimme/versions/go1.9.linux.amd64/src/sync/map.go:336 +0x150
github.com/cha87de/kvmtop/runners.lookup()
/home/travis/gopath/src/github.com/cha87de/kvmtop/runners/lookup.go:63 +0x363
github.com/cha87de/kvmtop/runners.initializeLookup(0xc4200de000)
/home/travis/gopath/src/github.com/cha87de/kvmtop/runners/lookup.go:21 +0x54
created by github.com/cha87de/kvmtop/runners.InitializeRunners
/home/travis/gopath/src/github.com/cha87de/kvmtop/runners/runners.go:13 +0x6f
```

```
<domain type='kvm' id='9'>
  <name>oma</name>
  <uuid>4b628d5b-212d-4eca-ab61-213715fdf63d</uuid>
  <memory unit='KiB'>1048576</memory>
  <currentMemory unit='KiB'>1048576</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <resource>
    <partition>/machine</partition>
  </resource>
  <os>
    <type arch='x86_64' machine='pc-i440fx-rhel7.5.0'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state='off'/>
  </features>
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>IvyBridge-IBRS</model>
    <vendor>Intel</vendor>
    <feature policy='require' name='ss'/>
    <feature policy='require' name='pcid'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='arat'/>
    <feature policy='require' name='tsc_adjust'/>
    <feature policy='require' name='stibp'/>
    <feature policy='require' name='ssbd'/>
    <feature policy='require' name='xsaveopt'/>
    <feature policy='require' name='pdpe1gb'/>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>destroy</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/libexec/qemu-kvm</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/oma.qcow2'/>
      <backingStore/>
      <target dev='vda' bus='virtio'/>
      <alias name='virtio-disk0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x07' function='0x0'/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/oma-catalog.qcow2'/>
      <backingStore/>
      <target dev='vdb' bus='virtio'/>
      <alias name='virtio-disk1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x09' function='0x0'/>
    </disk>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <alias name='usb'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <alias name='usb'/>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <alias name='usb'/>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <alias name='usb'/>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'>
      <alias name='pci.0'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <alias name='virtio-serial0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </controller>
    <interface type='network'>
      <mac address='52:54:00:f3:5d:80'/>
      <source network='default' bridge='virbr0'/>
      <target dev='vnet16'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <source path='/dev/pts/9'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
      <alias name='serial0'/>
    </serial>
    <console type='pty' tty='/dev/pts/9'>
      <source path='/dev/pts/9'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
    <channel type='unix'>
      <source mode='bind' path='/var/lib/libvirt/qemu/channel/target/domain-9-oma/org.qemu.guest_agent.0'/>
      <target type='virtio' name='org.qemu.guest_agent.0' state='connected'/>
      <alias name='channel0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0' state='disconnected'/>
      <alias name='channel1'/>
      <address type='virtio-serial' controller='0' bus='0' port='2'/>
    </channel>
    <input type='tablet' bus='usb'>
      <alias name='input0'/>
      <address type='usb' bus='0' port='1'/>
    </input>
    <input type='mouse' bus='ps2'>
      <alias name='input1'/>
    </input>
    <input type='keyboard' bus='ps2'>
      <alias name='input2'/>
    </input>
    <graphics type='spice' port='5907' autoport='yes' listen='127.0.0.1'>
      <listen type='address' address='127.0.0.1'/>
    </graphics>
    <sound model='ich6'>
      <alias name='sound0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </sound>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <alias name='video0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <alias name='redir0'/>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <alias name='redir1'/>
      <address type='usb' bus='0' port='3'/>
    </redirdev>
    <memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x08' function='0x0'/>
    </memballoon>
  </devices>
  <seclabel type='dynamic' model='dac' relabel='yes'>
    <label>+107:+107</label>
    <imagelabel>+107:+107</imagelabel>
  </seclabel>
</domain>

```

**Comment by cha87de** [comment]
@MyungChi this is somehow strange. does this error occur regularly / periodically or even always when you run kvmtop?

**Comment by MyungChi** [comment]
When that VM is activated, It always occured. 

I don't know go language. But I can try to debug if possible. Would U let me know how can I build binary with debug info ? Then I will check out source code and debug it.

**Comment by cha87de** [comment]
@MyungChi the new release https://github.com/cha87de/kvmtop/releases/tag/2.1.1 should hopefully fix the issues you reported. please let me know if you run into any other bugs. thanks for your help!
